org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.219
neo_version_range=[21.1,)
loader_version_range=[4,)

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

mod_id=hunger_reworked_reforged
mod_name=Hunger Reworked Reforged
mod_license=MIT
mod_version=1.0.3+neoforge_1.21.1
mod_authors=wu_meng, Liu Dongyu
mod_description=Changes the way food works

#Test dependencies
junit_version=5.9.2
junit_platform_version=1.9.2
mockito_version=4.11.0
